services:
  crauler:
    build:
      context: .
      dockerfile: ./dockerfile/Dockerfile.Dev
    volumes:
      - ./src:/app/src
      - ./output:/app/output
      - ./.env.docker.debug:/app/.env.debug
      - ./links_params.json:/app/links_params.json
    ports:
      - 5678:5678

  db:
    ports:
      - 5444:5432
    volumes:
      - postgres_parse_vol_dev:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: debug_db

volumes:
  postgres_parse_vol_dev:

secrets:
  db_password:
    file: ./secrets/debug_db_password
