services:
  crauler:
    container_name: crauler_parser_service
    build:
      context: ./
      dockerfile: dockerfile/Dockerfile.Prod
    expose:
      - 5001
    command: uvicorn src.main:app --host 0.0.0.0 --port 5001
    secrets:
      - db_password
    depends_on:
      - db

  db:
    container_name: parser_service_database_pg
    image: postgres:16-alpine
    expose:
      - 5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_DB: db
    secrets:
      - db_password
    volumes:
      - postgres_parse_vol:/var/lib/postgresql/data/

volumes:
  postgres_parse_vol:

secrets:
  db_password:
    file: ./secrets/prod_db_password
