FROM python:3.12-slim-bullseye as builder

RUN mkdir app
WORKDIR /app

COPY poetry.lock pyproject.toml ./
RUN pip install --no-cache-dir poetry \
  && poetry config virtualenvs.in-project true \
  && poetry install --with main --no-interaction --no-ansi \
  && rm -rf $(poetry config cache-dir)/{cache,artifacts}

FROM python:3.12-slim-bullseye

COPY --from=builder /app /app

WORKDIR /app
ENV PATH="/app/.venv/bin:${PATH}"


COPY src/ ./src
